apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "runo.fullname" . }}-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "runo.fullname" . }}-controller
subjects:
  - namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
    name: {{ include "runo.serviceAccountName" . }}-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "runo.fullname" . }}-cronjob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "runo.fullname" . }}-cronjob
subjects:
  - namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
    name: {{ include "runo.serviceAccountName" . }}-cronjob