# Default values for runo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1 # Set the number of replicas

image:
  repository: ghcr.io/aljoshare/runo # Set the image repository
  pullPolicy: IfNotPresent # Set the pull policy
  # Overrides the image tag whose default is the chart appVersion.
  tag: "" # Set the image tag

imagePullSecrets: [] # Set a image pull secret
nameOverride: "" # Override the name
fullnameOverride: "" # Override the full name

serviceAccount:
  create: true   # Specifies whether a service account should be created
  annotations: {}   # Annotations to add to the service account
  name: "" # The name of the service account to use.

podAnnotations: {} # Set additional annotations for the pod

podSecurityContext: {} # Set the security context for the pod
  # fsGroup: 2000

securityContext: {} # Set the security context for the container
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {} # Set the resources
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {} # Set node selectors

tolerations: [] # Set node tolerations

affinity: {} # Set pod (anti-)affinities

# Args for runo
args:
  dryRun: false # Specify whether runo should run in dry-run mode
  httpPort: 8080 # Set the port for the http endpoint (e.g. health, metrics, etc.)