name: check if commits are conventional
on: pull_request

jobs:
  conventional-commit:
    name: Check if all commits are conventional
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: convco
          version: latest
      - name: Check if all commits are conventional
        run: |
          git --no-pager log --decorate=short --pretty=oneline -n 50
          convco check